#!/usr/bin/env bash
# Install web-01 setup of nginx on server web-02 with custom response HEADER

# Update package list and install nginx and restart service
sudo apt-get -y update >/dev/null 2>&1
sudo apt-get -y install nginx >/dev/null 2>&1

# Set file paths
SRC="/etc/nginx/sites-available/default"
DOCROOT="/var/www/html/index.nginx-debian.html"
#REDIRECT=""
#ERRDIRECT=""
HEADER="\\\n\tadd_header X-Served-By \$HOSTNAME;\n"
# Change doc_root contents
echo "Holberton School" | sudo tee $DOCROOT


# Redirect /redirect_me to another page
new_string="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "42i ${new_string}" $SRC

# New 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_string1="\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"
sudo sed -i "44i $new_string1" $SRC

sudo sed -i "11i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf

sudo service nginx restart
