#!/usr/bin/env bash
# script that generates a MySQL dump and creates a compressed archive
if [ "$#" -eq 1 ]
then
    mysqldump -uroot -p"$1" --all-databases | sudo tee backup.sql
    tar -vczf "$(date '+%d-%m-%Y').tar.gz" backup.sql
else
    echo "Please enter database password"
fi
