#!/usr/bin/env bash
# Update task #0, service (init) must say that nginx is not running
sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo rm /run/nginx.pid # kill -HUP "$(cat /run/nginx.pid)"
