#!/usr/bin/env bash
# Update task #0, service (init) must say that nginx is not running
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
kill -9 "$(cat /run/nginx.pid)" # sudo rm /run/nginx.pid
