#!/usr/bin/env bash
# Bash script that Creates file /var/run/holbertonscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file and terminates when receiving a SIGQUIT or SIGTERM signal

FILE=/var/run/holbertonscript.pid
echo "$$" > "$FILE"
cleanup () {
    rm "$FILE"
    exit
}

while true
do
    echo "To infinity and beyond"
    trap 'echo "I hate the kill command"; cleanup' SIGTERM
    trap 'echo "Y U no love me?!"; cleanup' SIGINT
    trap 'cleanup' SIGQUIT
done
