#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 100.
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
# Otherwise, displays the number
# In a list format

i="1"
TEXT1="FizzBuzz"
TEXT2="Fizz"
TEXT3="Buzz"

while (( i<101 ))
do
    if (((( i % 15 )) == "0" )); then
	echo "$TEXT1"
    elif (((( i % 5 )) == "0" )); then
	echo "$TEXT3"
    elif (((( i % 3 )) == "0" )); then
	echo "$TEXT2"
    else
	echo "$i"
    fi
i=$(( i + 1 ))
done
