#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes:

TEXT="Hour"
h="0"
m="1"

while (( h<13 ))
do
    echo "$TEXT: $h"
    while (( m<60 ))
    do
	echo "$m"
	m=$(( m + 1 ))
    done
    m="1"
h=$(( h + 1 ))
done
